apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-dep
  labels: 
    app: db-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-dep
  template:
    metadata:
      labels:
        app: db-dep
    spec:
      containers:
      - name: db-dep
        image: legendarynight/project-db_service:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: development
